chore: refactor husky config

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,11 @@
+#!/bin/bash
+
+echo "🔎 Running lint-staged..."
 npx lint-staged
+
+if [ $? -ne 0 ]; then
+  echo "❌ Lint-staged failed. Commit aborted."
+  exit 1
+fi
+
+echo "✅ Lint-staged completed successfully!"
